- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: 
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: market-price
        spec:
          serviceName: market-price
          template:
            metadata:
              labels:
                app: market-price
            spec:
              containers:
              - image: "{{ image }}"
                name: market-price
                env:
                - name: REDIS_HOST
                  value: redis-master
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  value: "pQ3BTHiQSY"
          selector:
            matchLabels:
              app: market-price
      validate_certs: no
      namespace: discordbots
